# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acd803db074f012de2542e00bc428a230ece26eca43a84025727039f21f382020d338baf8a11cd1485b3d51752ed7f3442091ca31d77aa9569eff0860e269973

test:
  secret_key_base: 24a7c511049f657940c9b6fbd85674eec546368d08a9bc4a74a5fd5204c2f1977a8955ca4d77c0eaf48fff5244be20cbb8ef75d80e35d051979a99e9aa473a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
